### PR TITLE
Fixes for ghc 7.10

### PR DESCRIPTION
**Pull request by tkonolige**
I've fixed issues that stop your package from building under ghc 7.10.

### CODE REVIEW

**Comment by philopon** [comment]
Thanks for your PR! but I can't merge it. please fix build error on ghc-7.8 & 7.6.

**Comment by tkonolige** [comment]
I totally forgot about older versions. Should I use CPP `#defines` to fix it?

**Comment by philopon** [comment]
Please use cabal-macro.
[transformers-base](https://github.com/mvv/transformers-base/blob/d8bc0c87306ce9f9e7b8476aee7a6c341f511fac/src/Control/Monad/Base.hs#L8-10) source code maybe help you.

**Comment by tkonolige** [comment]
I cannot reproduce the travis ci errors locally. Can you?

**Comment by philopon** [comment]
It may be version dependent error.
Please use ghc-7.6/ghc-7.8 or see travis error and `git commit --amend`/`git push -f` to fix it.

**Comment by tkonolige** [comment]
I used ghc-7.6 and ghc-7.8 locally and could not reproduce the error. It appears to be a dependency tree issue. I'm not sure how this is possible because I only increased the upper bounds.

**Comment by philopon** [comment]
Hmm... sorry, I've gone and jumped to conclusions. I'll check it.

**Comment by philopon** [comment]
Okey, I fixed and merged it! thanks:smile:

Next version of haddocset is released when #20 fixed, but I'm in busy, so it may take some time.

**Pull request merged**
